name: Actions input test

on:
  workflow_dispatch:
    inputs:
      # boolean:
      #   description: Ignore 'use workflow from', run from tag that generated the docker image
      #   type: boolean
      #   required: false
      #   default: true
      option:
        description: Ignore 'use workflow from', run from tag that generated the docker image
        type: choice
        options:
          - You cannot change this
        required: false
        default: true
      tag:
        description: "Tag to deploy for media web. The workflow will run from the git tag that generated this docker image. `use workflow from` option is ignored for this workflow"
        required: true
  
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"