name: Actions input test

on:
  workflow_dispatch:
    # inputs:
    #   # boolean:
    #   #   description: Ignore 'use workflow from', run from tag that generated the docker image
    #   #   type: boolean
    #   #   required: false
    #   #   default: true
    #   option:
    #     description: Ignore 'use workflow from', run from tag that generated the docker image
    #     type: choice
    #     options:
    #       - You cannot change this
    #     required: false
    #     default: true
    #   tag:
    #     description: "Tag to deploy for media web. The workflow will run from the git tag that generated this docker image. \n \n `use workflow from` option is ignored for this workflow"
    #     required: true
  
jobs:
  hello-world:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: echo "Hello World"
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      # - name: Setup Git
      #   run: |
      #     git config user.name "GitHub Actions"
      #     git config user.email "github@miguel.com"

      - shell: bash
        run: git tag -f last-release

      - name: Push changes
        shell: bash
        run: |
          git push --force --tags
